name: flutter_wanandroid
description: Flutter Wanandroid App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.1.5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  base_library:
#    git:
#      url: git://github.com/Sky24n/FlutterRepos.git
#      path: base_library

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1
#  flustars: ^0.2.5
  # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  fluintl: ^0.1.3
  # Flutter 城市列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.1
  #数据库
  sqflite: ^1.1.0
  # https://github.com/flutterchina/dio
  dio: 1.0.13
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.0
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^0.8.0
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.0.2
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: 1.1.6
  # device_info
#  device_info: ^0.4.0+1
  # webview_flutter
#  webview_flutter: ^0.3.10+3
  webview_flutter: ^0.3.12+1
  flutter_webview_plugin: ^0.3.5
  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.0
  # Flutter 全局屏幕适配。https://github.com/flutterchina/auto_size
  auto_size:
      git:
        url: git://github.com/flutterchina/auto_size.git
#  flutter_screenutil: ^0.5.2
  #极光推送
#  jpush_flutter: 0.0.13
  jmessage_flutter: ^0.6.3
#  jmessage_flutter:
#    git:
#      url: https://github.com/hanjianchun/jmessage-flutter-plugin.git
  #极光IM
#  jmessage_flutter:
#    git:
#      url: https://github.com/jpush/jmessage-flutter-plugin.git
  #toast
  fluttertoast: ^3.0.4
  #加载特效
  flutter_spinkit: ^3.1.0
  #状态管理
  event_bus: ^1.0.1
  #图片选择控件
  image_picker: ^0.5.4
  #图片
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  #录音
  flutter_sound: ^1.4.3
  #文件目录
  path_provider: ^0.5.0
  #图片裁剪
  image_cropper: ^1.0.2
  #日历
#  table_calendar:
#    git: https://github.com/hanjianchun/table_calendar.git
  #日期选择
  flutter_datetime_picker:
    git: https://github.com/hanjianchun/flutter_datetime_picker.git
  #权限管理
  permission_handler: '^3.1.0'
  #时间线
#  timeline_list: ^0.0.4
  #文件选择
  file_picker: '^1.3.7'
  #微信分享
  fluwx: ^1.2.1+2
  #滚轮选择
  flutter_picker: ^1.0.13
  #手势处理
  simple_gesture_detector: ^0.1.3
  #日期处理插件
  date_utils: ^0.1.0+2
  #音频播放
  audioplayers: ^0.10.0
  #视频播放
  chewie: ^0.9.6
  video_player: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/ali_connors.png
    - assets/images/ali_connors_sml.png
    - assets/images/qrcode.png
    - assets/images/icon_wan_android.png
    - assets/images/ic_launcher_news.png
    - assets/images/guide1.png
    - assets/images/guide2.png
    - assets/images/guide3.png
    - assets/images/guide4.png
    - assets/images/splash_bg.png
    - assets/images/ic_tab_group_active.png
    - assets/images/ic_tab_group_normal.png
    - assets/images/ic_tab_home_active.png
    - assets/images/ic_tab_home_normal.png
    - assets/images/ic_tab_profile_active.png
    - assets/images/ic_tab_profile_normal.png
    - assets/images/ic_tab_shiji_active.png
    - assets/images/ic_tab_shiji_normal.png
    - assets/images/ic_tab_subject_active.png
    - assets/images/ic_tab_subject_normal.png
    - assets/images/logo-red.jpg
    - assets/images/chat_single.png
    - assets/images/chat_group.png
    - assets/images/public_group.png
    - assets/images/add.png
    - assets/images/cut.png
    - assets/images/ic_network_error.png
    - assets/images/ic_data_empty.png
    - assets/images/icon_index_online.png
    - assets/images/icon_chat_group.png
    - assets/images/icon_chat_jigou.png
    - assets/images/create_meeting.png
    - assets/images/create_mission.png
    - assets/images/create_schedule.png
    - assets/images/create_willblow.png
    - assets/images/create_will.png
    - assets/images/icon_group_list.png
    - assets/images/icon_send_message.png
    - assets/images/icon_schedule_edit.png
    - assets/images/icon_schedule_delete.png
    - assets/images/no_article.png
    - assets/images/work_notification.png
    - assets/images/work_functions.png
    - assets/images/idcard_icon.png

    - assets/data/china.json
    - assets/data/app.db

  fonts:
    - family: NotoSansSc
      fonts:
        - asset: assets/fonts/pingfang-normal.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
